//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerMall.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlowerDBEntities : DbContext
    {
        public FlowerDBEntities()
            : base("name=FlowerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_Collection> tb_Collection { get; set; }
        public virtual DbSet<tb_Comments> tb_Comments { get; set; }
        public virtual DbSet<tb_ConsumeData> tb_ConsumeData { get; set; }
        public virtual DbSet<tb_FlowerAdmin> tb_FlowerAdmin { get; set; }
        public virtual DbSet<tb_GoodsInfo> tb_GoodsInfo { get; set; }
        public virtual DbSet<tb_ReceAddress> tb_ReceAddress { get; set; }
        public virtual DbSet<tb_ShopCart> tb_ShopCart { get; set; }
        public virtual DbSet<tb_UserInfo> tb_UserInfo { get; set; }
        public virtual DbSet<tb_Order> tb_Order { get; set; }
        public virtual DbSet<tb_OrderSp> tb_OrderSp { get; set; }
    }
}
