//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Comments
    {
        public int CommID { get; set; }
        public Nullable<int> GoodID { get; set; }
        public string GoodSort { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CommTime { get; set; }
        public string CommImg { get; set; }
        public string ManagerComm { get; set; }
        public Nullable<int> Fabulous { get; set; }
        public string CommText { get; set; }
    
        public virtual tb_GoodsInfo tb_GoodsInfo { get; set; }
        public virtual tb_UserInfo tb_UserInfo { get; set; }
    }
}
