//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Collection
    {
        public int CollecID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> GoodID { get; set; }
        public string GoodName { get; set; }
        public Nullable<decimal> GoodPrice { get; set; }
        public string GoodImg { get; set; }
        public Nullable<int> GoodState { get; set; }
    
        public virtual tb_UserInfo tb_UserInfo { get; set; }
    }
}
