//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_GoodsInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_GoodsInfo()
        {
            this.tb_Comments = new HashSet<tb_Comments>();
        }
    
        public int GoodID { get; set; }
        public string GoodName { get; set; }
        public string GoodType { get; set; }
        public string GoodSort { get; set; }
        public string FlowerLanguage { get; set; }
        public string GoodMainImg { get; set; }
        public string GoodDataImg { get; set; }
        public Nullable<int> GoodStock { get; set; }
        public Nullable<int> GoodState { get; set; }
        public Nullable<int> GoodComments { get; set; }
        public Nullable<int> GoodMsales { get; set; }
        public Nullable<int> GoodCollection { get; set; }
        public Nullable<decimal> GoodPrice { get; set; }
        public Nullable<int> GoodFreight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Comments> tb_Comments { get; set; }
    }
}
