//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_OrderSp
    {
        public int DataID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> GoodID { get; set; }
        public string GoodName { get; set; }
        public string GoodType { get; set; }
        public string GoodSort { get; set; }
        public Nullable<decimal> GoodPrice { get; set; }
        public Nullable<int> GoodNums { get; set; }
        public Nullable<decimal> GoodSum { get; set; }
        public string GoodImg { get; set; }
    
        public virtual tb_Order tb_Order { get; set; }
    }
}
