//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Order()
        {
            this.tb_OrderSp = new HashSet<tb_OrderSp>();
        }
    
        public int OrderID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ReceName { get; set; }
        public string ReceAddr { get; set; }
        public string ReceTel { get; set; }
        public Nullable<int> GoodFreight { get; set; }
        public string GoodDiscount { get; set; }
        public string OrderMoney { get; set; }
        public Nullable<int> OrderState { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> PaymentTime { get; set; }
        public Nullable<System.DateTime> DeliverTime { get; set; }
        public Nullable<System.DateTime> ReceiveTime { get; set; }
        public string GoodNames { get; set; }
        public Nullable<int> UserVisible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_OrderSp> tb_OrderSp { get; set; }
    }
}
