//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ReceAddress
    {
        public int ReceID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ReceName { get; set; }
        public string ReceAddr { get; set; }
        public string ReceTel { get; set; }
    
        public virtual tb_UserInfo tb_UserInfo { get; set; }
    }
}
