//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_UserInfo()
        {
            this.tb_Collection = new HashSet<tb_Collection>();
            this.tb_Comments = new HashSet<tb_Comments>();
            this.tb_ReceAddress = new HashSet<tb_ReceAddress>();
            this.tb_ShopCart = new HashSet<tb_ShopCart>();
        }
    
        public int UserID { get; set; }
        public string UserLoginName { get; set; }
        public string UserLoginPwd { get; set; }
        public string UserPayPwd { get; set; }
        public string UserName { get; set; }
        public string UserTel { get; set; }
        public string UserSex { get; set; }
        public Nullable<int> UserMark { get; set; }
        public string UserImg { get; set; }
        public Nullable<int> UserCollection { get; set; }
        public Nullable<int> UserShopCort { get; set; }
        public Nullable<System.DateTime> UserDatetime { get; set; }
        public Nullable<int> UserState { get; set; }
        public Nullable<System.DateTime> SealTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Collection> tb_Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Comments> tb_Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ReceAddress> tb_ReceAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ShopCart> tb_ShopCart { get; set; }
    }
}
